apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: atomist
    app.kubernetes.io/name: lff-sdm
    app.kubernetes.io/part-of: lff-sdm
  name: lff
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: atomist
    app.kubernetes.io/name: lff-sdm
    app.kubernetes.io/part-of: lff-sdm
    atomist.com/workspaceId: AR12QA2B3
  name: lff-sdm
  namespace: lff
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: atomist
    app.kubernetes.io/name: lff-sdm
    app.kubernetes.io/part-of: lff-sdm
    atomist.com/workspaceId: AR12QA2B3
  name: lff-sdm
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "secrets", "serviceaccounts", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: atomist
    app.kubernetes.io/name: lff-sdm
    app.kubernetes.io/part-of: lff-sdm
    atomist.com/workspaceId: AR12QA2B3
  name: lff-sdm
  namespace: lff
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lff-sdm
subjects:
  - kind: ServiceAccount
    name: lff-sdm
    namespace: lff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: atomist
    app.kubernetes.io/name: lff-sdm
    app.kubernetes.io/part-of: lff-sdm
    atomist.com/workspaceId: AR12QA2B3
  name: lff-sdm
  namespace: lff
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lff-sdm
      atomist.com/workspaceId: AR12QA2B3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        atomist.com/k8vent: '{"webhooks":["https://webhook.atomist.com/atomist/kube/teams/AR12QA2B3"]}'
      labels:
        app.kubernetes.io/managed-by: atomist
        app.kubernetes.io/name: lff-sdm
        app.kubernetes.io/part-of: lff-sdm
        app.kubernetes.io/version: "1"
        atomist.com/workspaceId: AR12QA2B3
    spec:
      containers:
        - env:
            - name: ATOMIST_CONFIG_PATH
              value: /opt/atm/client.config.json
            - name: ATOMIST_GOAL_SCHEDULER
              value: kubernetes
            - name: ATOMIST_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: FORCE_COLOR
              value: "1"
          image: atmhoff/lff-sdm:1.0.0
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
          name: lff-sdm
          ports:
            - containerPort: 2866
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 384Mi
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
            - mountPath: /opt/atm
              name: lff-sdm
              readOnly: true
      serviceAccountName: lff-sdm
      terminationGracePeriodSeconds: 180
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: docker-sock
        - name: lff-sdm
          secret:
            defaultMode: 288
            secretName: lff-sdm
